### ISSUE TITLE
Add file type checking to planex-fetch

### ISSUE THREAD

**Issue by euanh** [xenserver/planex#123]
planex-downloader checked whether the result of a download looked like an archive, and retried the download if it didn't.  planex-fetch should do the same thing.

There is a Python library to wrap around libmagic, but it is more or less as ugly as just shelling out to file, as downloader used to do.

**Comment by simonjbeaumont** [comment]
Removing bug label now fetch has been fixed to not blat the file in the failure case. The enhancement suggestion remains valid.
