### ISSUE TITLE
Add bash completion support

### ISSUE THREAD

**Issue by euanh** [xenserver/planex#134]
http://tldp.org/LDP/abs/html/tabexpansion.html

**Comment by simonjbeaumont** [comment]
@euanh: This looks pretty handy:

https://github.com/kislyuk/argcomplete

"argcomplete - Bash tab completion for argparse"

**Comment by simonjbeaumont** [comment]
Looks like we could add a line similar to:

```
argcomplete.autocomplete(parser)
```
after our normal parsing definition.

**Comment by djs55** [comment]
Aha, I was wondering if something like that existed!

**Comment by simonjbeaumont** [comment]
Boom :boom:
