### ISSUE TITLE
Planex commands should be verbose by default unless --quiet is specfied

### ISSUE THREAD

**Issue by euanh** [xenserver/planex#147]
This would match the behaviour of mock, rpmbuild and createrepo, and make it possible to have a single $(QUIET) variable controlling the logging behaviour of all commands in Makefile.rules

**Comment by simonjbeaumont** [comment]
This should probably be defined with a `?=` like `$(TOPDIR)` so that it can be set in the project's Makefile too.

**Comment by simonjbeaumont** [comment]
Started work on this branch: https://github.com/xenserver/planex/compare/xenserver:master...simonjbeaumont:quiet
