### ISSUE TITLE
planex-pin --version and rpm -q planex disagree

### ISSUE THREAD

**Issue by euanh** [xenserver/planex#178]
```
$ planex-pin --version
planex-pin 0.6.0
```

```
$ rpm -q planex
planex-0.6.0-1+s0+0.6.0+233+g32a45d7.fc21.noarch
```

I don't think it will be possible to make them agree without quite a bit of hassle, though.  We would need to find a way to feed the pinned version number through to setuptools.   May just have to close this one as `wontfix`.

**Comment by simonjbeaumont** [comment]
:rage1:

We should fix this by updated the planex spec file to inject its version into the setup tools.

**Comment by euanh** [comment]
This bit of sed would do it:
sed -e "s/\(version='\)[^'\"]\+/\1<new version>/g" setup.py

**Comment by simonjbeaumont** [comment]
With fix from #189:

```
$ sudo rpm -Uvh --force _build/RPMS/noarch/planex-0.6.0-1+s0+0.6.0+235+g9bba4e1.el6.noarch.rpm
Preparing...                ########################################### [100%]
   1:planex                 ########################################### [100%]
$ rpm -q planex
planex-0.6.0-1+s0+0.6.0+235+g9bba4e1.el6.noarch
$ planex-pin --version
planex-pin 0.6.0-1-s0-0.6.0-235-g9bba4e1.el6
```

**Comment by simonjbeaumont** [comment]
Still don't have the `%{BuildArch}` in the version. @euanh do you want that too?

**Comment by euanh** [comment]
I think this is close enough.   As a pure Python project, Planex is very likely always to be a noarch package, so I don't think including the BuildArch has much value.   The minor differences in formatting between rpm -q and planex-foo --version aren't a problem either - it's very clear what version of the code you are running.
