### ISSUE TITLE
planex-cache fails if no loopback repository is defined

### ISSUE THREAD

**Issue by euanh** [xenserver/planex#181]
planex-cache now allows you to change the name of the loopback repository, but it still insists that you have one.    If you are only building a couple of packages which don't have mutual dependencies, you might not want or need a loopback repository.   planex-cache should have a 'no loopback' option to cater for this situation.

**Comment by simonjbeaumont** [comment]
Linked a pull request to add this option. Where would we make use of such an option since the `Makefile.rules` don't currently specify a loopback repo but just let it default (to `mock`).
