### ISSUE TITLE
planex-pin: If the treeish isn't specified when pinning, we should assume 'HEAD'

### ISSUE THREAD

**Issue by jonludlam** [xenserver/planex#200]
see issue #199

**Comment by simonjbeaumont** [comment]
The internal functions default to this...

**Comment by simonjbeaumont** [comment]
Do we want it to default to `HEAD` which will convert it to the static commit that `HEAD` is currently at or to whatever the active branch is.

The former would not generate new builds with new commits in the locally checked out repo...

@euanh: :question::bangbang:

**Comment by euanh** [comment]
Fixed by 7c49282d546664720bbc1add05bc03e396c0b1e4
