### ISSUE TITLE
Cache and out of disk space

### ISSUE THREAD

**Issue by djs55** [xenserver/planex#223]
Should failure to cache be a hard failure, or a soft one? I'm seeing this atm:
```
07:37:32 00:07:44 O: File "/usr/bin/planex-cache", line 9, in <module>
07:37:32 00:07:44 O: load_entry_point('planex==0.7.1-1.el7.centos', 'console_scripts', 'planex-cache')()
07:37:32 00:07:44 O: File "/usr/lib/python2.7/site-packages/planex/cache.py", line 263, in _main
07:37:32 00:07:44 O: main(sys.argv[1:])
07:37:32 00:07:44 O: File "/usr/lib/python2.7/site-packages/planex/cache.py", line 244, in main
07:37:32 00:07:44 O: add_to_cache(cachedirs, pkg_hash, build_output)
07:37:32 00:07:44 O: File "/usr/lib/python2.7/site-packages/planex/cache.py", line 104, in add_to_cache
07:37:32 00:07:44 O: shutil.copy(os.path.join(build_dir, fname), cache_output_dir)
07:37:32 00:07:44 O: File "/usr/lib64/python2.7/shutil.py", line 119, in copy
07:37:32 00:07:44 O: copyfile(src, dst)
07:37:32 00:07:44 O: File "/usr/lib64/python2.7/shutil.py", line 84, in copyfile
07:37:32 00:07:44 O: copyfileobj(fsrc, fdst)
07:37:32 00:07:44 O: IOError: [Errno 28] No space left on device
```

**Comment by thomassa** [comment]
If it's a soft one, we need to make sure that it is still conspicuous.
Otherwise the risk is that people won't notice, but will just be unhappy about how long the build takes.

**Comment by djs55** [comment]
I think this might have left a corrupt cache entry -- I retried the build and a later component failed to find this one (it was a build dependency). So planex thought it existed but yum disagreed.

**Comment by euanh** [comment]
Currently `planex-cache` does not try to manage the size of the cache.  It should!   I thought we had an issue for this, but there wasn't one so I've created #224.    When we add cache management, out of space should be a hard error because it should only occur when the disk is really full.

Are you having this problem on your own machine or in xenbuilder?   This shouldn't happen in xenbuilder because it manages the cache for us.

**Comment by djs55** [comment]
It's on xenbuilder -- check out trunk-btrfs-2:

https://xenbuilder.uk.xensource.com/logs/carbon/trunk-btrfs-2/102996/cam/core/xe-phase-1-build.out

**Comment by euanh** [comment]
Hmm.   Looks like xenbuilder isn't managing the cache quite right!   We made change 18c5e0aed21862e27abf738a9915f3632f8b5d57 (touch the files we use) to help it...

**Comment by djs55** [comment]
OK, that's useful to know!
I get repeated build failures with xenbuilder because of (I assume) a broken cache entry. Bumping the release version of the semi-cached thing has caused it to rebuild and my local build is working ok.
