### ISSUE TITLE
Switch from urllib2 and curl to requests

### ISSUE THREAD

**Issue by euanh** [xenserver/planex#227]
http://www.python-requests.org/en/latest/

Might not be suitable for planex-fetch - we use libcurl to spool directly to disk rather than buffering tarballs in memory.

**Comment by mseri** [comment]
We have been thinking of using urlgrabber like yum, but that will never be ported to python 3 and it's been deprecated since fedora 22. Using requests allows us to move on to python3 and have a cleaner api for http calls
