### ISSUE TITLE
Observation: build problems after switching branches

### ISSUE THREAD

**Issue by lindig** [xenserver/planex#361]
With build operation being expensive, Planex must walk a fine line between maximising sharing/caching and ensuring correctness. I observed that after switching branches I was working with an outdated `_build/deps` file, causing the build to fail. 

If switching branches without a `make clean` is common, one idea would be to encode the name of the branch into the `deps` (or the `_build`) file. In general, one could think about what build artefacts should be shared between branches and which not.

**Comment by mseri** [comment]
This could be easily fixed namespacing the builds.
If we link `_build/current` to `_build/branch-name` at the beginning of the make and work in `_build/current` it should manage multiple branches fine.

**Comment by MarkSymsCtx** [comment]
That sounds good, but if there are pinned repos then the PINS repo would need to be switched the same branch and then the repos would need to be resynced as well. Probably easier to just use different folders for the different top level branches
