### ISSUE TITLE
.gitignore includes SOURCES/* but maybe shouldn't

### ISSUE THREAD

**Issue by lindig** [xenserver/planex#373]
The `.gitignore` includes

```
SOURCES/*.tar.gz
SOURCES/*.tar.bz2
SOURCES/*
```
and I'd like to suggest to remove these lines. As these files are used by SPEC files I see no reason to ignore them. In particular, changes here are not reported by Git as a result.  SOURCES/ typically includes patches and why should they be ignored?

**Comment by euanh** [comment]
This comment is about the xenserver-specs repo, not planex.   It has now been fixed in xenserver-specs.
