### ISSUE TITLE
planex-build-mock uses wrong path when calling createrepo

### ISSUE THREAD

**Issue by euanh** [xenserver/planex#457]
`planex-build-mock` expects to be able to run in `${PWD}/RPMS`, but it should be using `_topdir/RPMS`.   To get this, we need to pass planex-bulid-mock the same `--define "_topdir _build"` argument which we pass to other utilities, then we can ask the RPM library to construct the path for us.

https://github.com/xenserver/planex/blob/6d07f16af1356c1d8ef239a19d154adb76ce49c6/planex/cmd/mock.py#L182

Currently, this bug only makes the build break if you delete the RPMS symlink.   In future we plan to get rid of this symlink entirely.

**Comment by MarkSymsCtx** [comment]
It also effects new workspaces which don't get the RPMs symlink after 4fc2f6285bf3bd84f254f28edaa53411c07f38c3
