### ISSUE TITLE
Clone does not understand the new link/pin format

### ISSUE THREAD

**Issue by euanh** [xenserver/planex#500]

**Comment by mseri** [comment]
`planex-clone` will work at follows:
- clone any source, if archives are present and point to a git repoository clone and unpack them and replace files from the archives as happens in the spec files. If the unpacked repo is a git repository, git commit the changes with a clear commit.
- if more than a patchqueue is present, exit saying that only one is supported
- if a patchqueue is present, do what the old planex clone was doing and clone and apply it
