### ISSUE TITLE
Decide what to do with planex-manifest

### ISSUE THREAD

**Issue by euanh** [xenserver/planex#502]
planex-manifest does not work very well and does not understand the new link file format.

Ideally, tracking what went into a build should be handled outside planex.   If we really want to keep track of the git hash of the commit which went into a package, we can use .gitattributes.

If we remove planex-manifest, we can also get rid of repository.py, most if not all of git.py and most of utils.py.

**Comment by mseri** [comment]
Note: planex-manifest output is meaningless for the new link and pin files

**Comment by mseri** [comment]
The current plan is the following:
- remove planex-manifest
- add metadata in the spec file to keep some relevant information (it can be disabled and removed in an easy way)
- once a better way is in place internally get rid also of that
