### ISSUE TITLE
Refactor link file parsing logic

### ISSUE THREAD

**Issue by euanh** [xenserver/planex#503]
Previously we loaded the contents of .lnk files into Link objects, specified in link.py.   When we added the v2 schema, we added some logic to paper over the differences between the two forms.   In this refactoring, we have changed the way we handle links - rather than consulting the link object, the Spec object has an API for adding 'resources' which handles overriding of existing resources.   This simplifies the logic in the tools and tests, so seems to be an improvement.

With this change we can get rid of the Link class entirely and load and parse the JSON in the new load() function (currently in spec.py).

**Comment by mseri** [comment]
PINS version:

1. deprecated:
    - `URL`: source repository url
    - `commitish`: source repository tag/commitish
    - `patchqueue`: name appended to the generated patchqueue tarball
    - `base`: base repository url (for PQ pins, and used only by planex-clone afaik)
    - `base_commitish`: base repository commitish (for PQ pins, and used only by planex-clone afaik)
    - `sources`: folder for additional sources
    - `patches`: ??? not sure

v2.
    - `source`: unused
    - `patch`: contains `URL` and `commitish` pointing to a tarball with extra files (sources and patches)
    - `patchqueue`: contains `URL` and `commitish` pointing to a tarball with patches and a series file

v3.
    - `sourceX`: contains `URL` and `commitish` pointing to a "blob" overriding or adding  `sourceX` in the spec
    - `patchX`:  contains `URL` and `commitish` pointing to a "blob" overriding or adding `patchX` in the spec
    - `archiveX`: contains `URL` and `commitish` pointing to a tarball with extra files (used when looking for the files)
    - `patchqueueX`: contains `URL` and `commitish` pointing to a tarball with patches and a series file

**Comment by mseri** [comment]
@euanh please update the above is any of the information is wrong. What was `patches` in pins v1 for?

**Comment by mseri** [comment]
I have not yet deleted the Link class, I think I will postpone it for now
