### ISSUE TITLE
Define .rc file mechanism to allow for project and personal settings overrides

### ISSUE THREAD

**Issue by MarkSymsCtx** [xenserver/planex#536]
After the behaviour change in planex-pin which now requires a `-o <file>` option to write to a pin file there have been a number of complainants about the behaviour change. The reasons are manifest but prmarily down to the tool being agnostic and not having knowledge baked in about usage. This could be addressed by defining a .rc file mechanism to allow for local (both per user ~ and project, checked into git) setting to define required behaviour.

**Comment by srowe** [comment]
I propose that we read the files `/etc/planexrc` and `~/.planexrc` (in that order) using `SafeConfigParser` to process INI style options in sections.

**Comment by srowe** [comment]
Actually let's use `RawConfigParser` otherwise there will probably be interactions between interpolation and RPM macros.

**Comment by MarkSymsCtx** [comment]
I think we also want .planexrc (i.e. local working dir copy) so that it can be checked in at a project level.

**Comment by srowe** [comment]
Good idea.
