### ISSUE TITLE
Support for mercurial

### ISSUE THREAD

**Issue by matelakat** [xenserver/planex#54]
`planex-clone` should be able to clone mercurial sources.

**Comment by euanh** [comment]
If we need to support mercurial repositories, we can probably do it using git's remote helpers:

$ git --version
git version 2.1.0
$ sudo yum install git-remote-hg
...
$ git config --global remote-hg.hg-git-compat true
$ git clone hg::http://path/to/repo.hg
Cloning into 'repo.hg'...
requesting all changes
adding changesets
adding manifests
adding file changes
added 42 changesets with 42 changes to 42 files
Checking connectivity... done.
$ cd repo.hg
$ hg status
abort: no repository found in '/tmp/repo.hg' (.hg not found)!
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
